version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: yarn dev
    ports:
      - "5001:5000" # host:container
    environment:
      DATABASE_URL: postgres://eli_user:eli_password@postgres:5432/eli_test_strips
      NODE_ENV: development
    volumes:
      - ./backend:/usr/src/app/backend
      - ./uploads:/usr/src/app/uploads
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: eli_test_strips
      POSTGRES_USER: eli_user
      POSTGRES_PASSWORD: eli_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
